### PR TITLE
Rate limiting

### PR DESCRIPTION
**Pull request by szb0018**

### CODE REVIEW

**Comment by compwright** [comment]
Thanks for this feature, but I don't really think this belongs in the API client itself.

* It would be better for rate limit functionality to wrap around the API client (similar to how the pagination utility does) rather than be embedded at a low level.
* I am not keen on introducing the dependency on https://github.com/eventEmitter/request-rate-limiter since someone might want to use a different rate limiter.

For these reasons, I'm declining this PR. I would be happy to entertain a PR that replaces the `purest` client with something like Axios. You could then pass in an instance of Axios that has an interceptor configured to handle HTTP 429 and implement a backoff strategy using `request-rate-limiter` or any other.

Outside of that, this should probably just be a function in your application that wraps the API call.

**Comment by szb0018** [comment]
I disagree. The rate limiting is a requirement that is enforced by the API - it is not an application feature. Additionally, the point of this library is to hide away the implementation details of how the requests are built - which makes it impossible for me to throttle the requests from outside the library. As such it makes sense to have the library implement the rate limiting.

To your other point, I don't have any choice in which rest library the module uses internally. So why should I have any control over the rate limiting library?

I also can't effectively create a wrapper around this library, because of features like pagination and bulk activity waiting which are internally following links and making calls that a wrapper cannot intercept and manage.

**Comment by compwright** [comment]
I don't really see your point, since all you'd have to do to handle this with a wrapper function is to call the desired API method, catch the error, implement your back-off strategy, repeat the original API call, and resolve the original promise with that result. This is very similar to what the bundled pagination function does. The calls would still be made by the library itself.

You're not wrong about needing to account for rate limiting somehow. If we were gonna do this right, we would rate limit proactively (which I believe the AWS SDK for Javascript does) so that we avoid having the 429 errors happen altogether.

My only quibble is where and how to implement this. Given the lines of code, external dependency, and complexity added, it just doesn't smell right.

If you'd like, I would be happy to work on another release that replaces purest with the much more extensible axios, and provide an example of a rate-limit-aware retry interceptor.

**Comment by szb0018** [comment]
I would be curious to see how the AWS SDK handles this. It seems silly to me to have to re-implement the same rate-limiting in every project that needs to use constant contact; violates the principle of reuse.

I agree with your point that most cases could be handled by a wrapper, either proactively or reactively. The cases that I cannot handle with a wrapper are pagination and waiting on bulk operations. In both cases the library makes multiple requests, but exposes no way for me to intercept the subsequent requests and throttle them. I could handle the exceptions, but, particularly in the case of pagination, I lose the context of the request and have to start over.

I am not familiar with axios, but if it provides a way of injecting an interceptor into the underlying http client, then that would allow a wrapper to throttle even requests that it doesn’t know about.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by compwright** [comment]
Yeah, that's exactly how axios works - similar to the hold $http interceptors from Angular 1.x. It has recently caught on in the React and Vue.js communities.

https://github.com/axios/axios

**Comment by szb0018** [comment]
I’ll do some reading on it then. Regardless, until we convert this library over I can’t fully implement a wrapper that handles rate limiting all requests.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
